### ISSUE TITLE
Oauth required?

### ISSUE THREAD

**Issue by jesseleite** [zenapply/php-bitly#1]
Why does this package require browser username and password to new up a client instance?  Shouldn't it ask for the API key provided by bitly?

**Comment by tylercd100** [comment]
Hey Jesse,

Version 1.2.1 uses the deprecated API Key option -->
https://github.com/zenapply/php-bitly/tree/1.2.1

To my understanding, Bitly is attempting to phase out their old system with
a new one that uses OAuth2.

Please let me know if I missed something!

Here is a snippet from http://dev.bitly.com/authentication.html
[image: Inline image 1]

**Comment by tylercd100** [comment]
Oops, guess I cant share images on github... here is the image http://pasteboard.co/b7PrKr7wY.png

**Comment by tylercd100** [comment]
I guess I did miss something. You can apparently generate a [developer access token for OAuth2](https://bitly.com/a/oauth_apps) so there is no need for username and password combo. I will update this package to version 3 to fix this. Thanks for pointing it out!

**Comment by tylercd100** [comment]
Done! https://github.com/zenapply/php-bitly/tree/3.0.0

**Comment by jesseleite** [comment]
Nice, thanks for the update!
